Update release-to-discord.yml

diff --git a/.github/workflows/release-to-discord.yml b/.github/workflows/release-to-discord.yml
--- a/.github/workflows/release-to-discord.yml
+++ b/.github/workflows/release-to-discord.yml
@@ -12,8 +12,13 @@ jobs:
         env:
           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
         run: |
+          if [ -z "$DISCORD_WEBHOOK" ]; then
+            echo "❌ ERROR: DISCORD_WEBHOOK is empty!"
+            exit 1
+          fi
+
           RELEASE_NAME="${{ github.event.release.name }}"
-          RELEASE_BODY=$(echo "${{ github.event.release.body }}" | jq -Rsa .)
+          RELEASE_BODY=$(echo "${{ github.event.release.body }}" | jq -Rs .)
 
           curl -H "Content-Type: application/json" \
           -X POST \
@@ -26,4 +31,4 @@ jobs:
               "url": "'"${{ github.event.release.html_url }}"'",
               "color": 16776960
             }]
-          }' $DISCORD_WEBHOOK
+          }' "$DISCORD_WEBHOOK"
